export const items = [
  {
    id: Math.random(),
    title: "Breakfast meal",
    description: "Breakfast: Important morning meal for energy and nutrients.",
    price: "30.00 $",
    category: "Breakfast",
    imgUrl: "imgs/Dinner1.jpg",
  },
  {
    id: Math.random(),
    title: "Lunch meal",
    description: "Lunch: Midday meal for energy recharge and focus.",
    price: "80.00 $",
    category: "Lunch",
    imgUrl: "imgs/Lunch1.jpg",
  },
  {
    id: Math.random(),
    title: "Lunch meal",
    description: "Lunch: Midday meal for energy recharge and focus.",
    price: "70.00 $",
    category: "Lunch",
    imgUrl: "imgs/Lunch2.jpg",
  },
  {
    id: Math.random(),
    title: "Dinner meal",
    description: "Dinner: Evening meal before sleep for nourishment and relaxation.",
    price: "30.00 $",
    category: "Dinner",
    imgUrl: "imgs/Dinner1.jpg",
  },
  {
    id: Math.random(),
    title: "Dinner meal",
    description: "Dinner: Evening meal before sleep for nourishment and relaxation.",
    price: "40.00 $",
    category: "Dinner",
    imgUrl: "imgs/Dinner2.jpg",
  },
  {
    id: Math.random(),
    title: " Breakfast meal",
    description: "Breakfast: Important morning meal for energy and nutrients.",
    price: "25.00 $",
    category: "Breakfast",
    imgUrl: "imgs/breakfast2.png",
  },
];